# Generated by Django 5.1.6 on 2025-04-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_savedresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedResult',
        ),
    ]
